name: Build & Push API image

on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/test-api.yml   # <— reuse your existing test job (or copy steps here)

  build:
    name: Build & push
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/banking-fraud-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/banking-fraud-api:${{ github.sha }}
