name: Run API tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run tests
        env:
          SKIP_MODEL_STARTUP: "1"              # keeps your app from loading the model in CI
          PYTHONPATH: ${{ github.workspace }}  # <<< makes "import app..." work
        run: |
          pytest -q tests
